# 主题模式
theme: 
  switch: true 
  default: auto

# 网站图标
favicon:
  logo: /img/logo.svg
  icon16: /img/logo.svg
  icon32: /img/logo.svg
  appleTouchIcon: apple-touch-icon.png
  webmanifest: /site.webmanifest
  visibilitychange: true
  hidden: failure.ico
  showText: (/≧▽≦/)嘿！骗你的！
  hideText: (●—●)哎呀，崩溃了！

# 用户信息
user:
  name: Grain Rain # 侧边栏与其他位置的姓名标识
  first_name: Rain
  last_name: Grain # 顶栏姓名标识
  avatar: https://pic.imgdb.cn/item/63ba7e07be43e0d30ed318cd.jpg
  email: 23548399650@qq.com
  domain: https://grainrain.site/
  describe: 世事漫随流水 算来一生浮梦。
  ruleText: <br> 暂不接受友链申请，仅收录OJ链接。

# 顶栏 | 导航栏 | TopBars

top_bars:
  - title: Home
    url: /
  
  - title: Archives
    url: '#'
    noswup: true
    children:
      - title: year
        url: /archives/
      - title: Categories
        url: /categories/

  - title: Links
    url: /links/
    noswup: true

  - title: About
    url: /about/
    noswup: true

# 侧栏

## 社交链接
sidebar:
  social:  # 社交地址
    - name: github
      icon: fab fa-github   
      url: https://github.com/GrainRainy
    
    - name: luogu
      icon: /img/luogu.png
      url: https://www.luogu.com.cn/user/746291

## 打字动画

  typedTextPrefix: Stay
  typedText: [ 'Hungry | Stay Foolish' ]

## 侧边信息

  info: # 个人信息
    - key: Ages
      val: 16
    - key: Address
      val: Hebei - China  


# 横幅 Banner

banner:
  index:
    type: video
    bgurl: https://cdn.moji.com/websrc/video/autumn20190924.mp4
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!

  archive: 
    type: img
    bgurl: https://pic.imgdb.cn/item/63ba7f5cbe43e0d30ed4dad0.jpg

  about:
    type: img
    bgurl: https://pic.imgdb.cn/item/63ba97c1be43e0d30e0306c3.jpg
  
  links: 
    type: img
    bgurl: https://pic.imgdb.cn/item/63ba7f83be43e0d30ed522ad.jpg


# 分类卡片

categorie_card:
  enable: true
  len: 2
  list: ["数据结构", "图论"]

# 归档页

archive:
  type: more # less / more


# 页脚

footer:
  copyrightYear: 2022
  
  powered:
    enable: false
  
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 12/25/2022 17:00:00

# 文章Artical

post_pagination: 
  enable: true 
  type: small # large || small


## 目录

toc:
  enable: true
  list_number: true
  max_depth: 4
  min_depth: 1


# 百度SEO
baidu_push: true

# 评论
comment:
  twikoo:
    enable: true
    visitor: true
    envId: https://twikoo-comment-api-eight.vercel.app/


# 链接页配置，请见 /source/_data/links.yml


# 字数统计
wordcount:
  enable: false
  count: true
  time: true

# KaTeX
katex:
  copy_tex: true
  global: true
  options: {}

# 站内搜索
search:
  enable: true
  type: local

# 右下角悬浮按钮块
rightside:
  readmode: true
  aside: true 

highlight:
  theme: true 
  title: default
  copy: true
  lang: true
  code_word_wrap: fasle 
  height_limit: 700 # 超出时，显示折叠按钮